// toern_prototypes.h — AUTO-GENERATED Arduino-style forward declarations for the
// TŒRN sketch (toern.ino + all toern_*.ino concatenated into one TU).
#ifndef TOERN_PROTOTYPES_H
#define TOERN_PROTOTYPES_H

#include "Arduino.h"
#include "Audio.h"
#include "FastLED.h"
#include "i2cEncoderLibV2.h"
#include "MIDI.h"
#include "icons.h"          // defines `enum IconType` (used in a few prototypes)

#ifndef NUM_ENCODERS
#define NUM_ENCODERS 4
#endif
#ifndef SAMPLE_BROWSER_NAME_MAX
#define SAMPLE_BROWSER_NAME_MAX 65
#endif
enum class DrawRFullMuteUnmuteMode : uint8_t;   // defined in toern.ino

// --- forward declarations of sketch types (none are passed by value) ---
struct SliderDefEntry; struct Note; struct MidiSettings; struct SliderMeta;
struct PendingNoteEvent; struct CachedSample; struct PendingNote; struct Mode;
struct Sample; struct Device; struct GlobalVars; struct FilterTarget;
struct GainTransition; struct HarmonicAnalysis; struct BasePagePattern;
struct Ripple; struct MenuPage; struct PeakScanState;
enum ValueDisplayMode : uint8_t; enum ParameterType : uint8_t;
enum FilterType : uint8_t; enum SynthTypes : uint8_t; enum MidiSetTypes : uint8_t;
enum SettingArray : uint8_t;

// --- function prototypes ---
bool enqueuePendingNote(uint8_t pitch, uint8_t velocity, uint8_t channel, uint8_t livenote);
bool dequeuePendingNote(PendingNote &out);
int readTouch1Raw();
int readTouch2Raw();
bool getSpkrEnabled();
void setSpkrEnabled(bool enabled);
bool getChildLockEnabled();
void setChildLockEnabled(bool enabled);
static inline bool isPaintableDrawRow(unsigned int y);
FLASHMEM void noteUserActivity();
bool drawRFullMuteIsActive();
FLASHMEM bool isChildVoiceDisabled(int channel);
FLASHMEM bool isChildVoiceMuted(int channel);
FLASHMEM void enforceChildModeRestrictions();
void initSliderDefTemplates();
FLASHMEM void applyStereoChannelRouting();
void stopSynthChannel(int ch);
static inline void resetMidiPressedKeyCount11to14();
static inline void applyExternalFastFilter(uint16_t value14);
void allOff();
FLASHMEM void setVelocity();
void staticButtonPushed(i2cEncoderLibV2 *obj);
void staticButtonReleased(i2cEncoderLibV2 *obj);
void staticThresholds(i2cEncoderLibV2 *obj);
void encoder_button_pushed(i2cEncoderLibV2 *obj, int encoderIndex);
void encoder_button_released(i2cEncoderLibV2 *obj, int encoderIndex);
void handle_button_state(i2cEncoderLibV2 *obj, int encoderIndex);
bool match_buttons(const uint8_t states[], int b0, int b1, int b2, int b3);
bool was_buttons_0000(const uint8_t prevStates[]);
bool was_not_buttons_0000(const uint8_t prevStates[]);
uint32_t hashString(const String &str);
static void resetCtrlModeState();
FLASHMEM void showCtrlVolumeChange(int volume);
FLASHMEM void showInputGainOverlay(int gain, int maxGain);
void refreshCtrlEncoderConfig();
void switchMode(Mode *newMode);
void checkFastRec();
void checkMode(const uint8_t currentButtonStates[NUM_ENCODERS], bool reset);
FLASHMEM void applySgtl5000CodecOutputPath();
void initSoundChip();
void initSamples();
void checkCrashReport();
void initEncoders();
FLASHMEM void loadColorSchemeAndBrightness();
FLASHMEM void loadLedModeEarlyFromEEPROM();
void setup();
void initGlobalVars();
void setEncoderColor(int i);
int getBatteryRaw();
int getBatteryPercent();
bool getBatteryWarningActive();
void checkEncoders();
void filtercheck();
void checkButtons();
void exitMenuFromTouchInput();
void checkTouchInputs();
void animateSingle();
void checkSingleTouch();
void _checkMenuTouch();
void checkPendingSampleNotes();
void showDoRecord();
void checkSerialColors();
void loop();
FLASHMEM void triggerExternalOneBlink();
FLASHMEM void updateExternalOneBlink();
float getNoteDuration(int channel);
FLASHMEM void shiftNotes();
void tmpMuteAll(bool pressed);
static void silenceAllVoicesForDrawRGlobalMute();
static void syncMuteArraysToSmp();
FLASHMEM void enterDrawRFullMute();
FLASHMEM void exitDrawRFullMute(DrawRFullMuteUnmuteMode mode);
FLASHMEM void toggleMute();
void deleteActiveCopy();
void play(bool fromStart);
void pause(bool skipSave);
void playSynth(int ch, int b, int vel, bool persistant);
void handlePageSwitch(int newEdit);
void playNote();
void checkPages();
void unpaint();
void playFillNote();
void triggerGridNote(unsigned int globalX, unsigned int y);
void paint();
void toggleCopyPaste();
void clearNoteChannel(unsigned int c, unsigned int yStart, unsigned int yEnd, unsigned int channel_to_clear, bool singleModeActive);
FLASHMEM void updatePreviewVolume();
FLASHMEM void updateLineOutLevel();
void updateBrightness();
FLASHMEM void switchSubPattern();
static void reverseChannelInMemory(uint8_t channel);
static void refreshSamplerChannel(uint8_t channel);
static void applyChannelDirection(uint8_t channel, int8_t targetDir);
FLASHMEM void updateBPM();
FLASHMEM void setVolume();
void showExit(int index);
void showLoadSave();
void showSamplePack();
void loadSamplePack(unsigned int pack_id, bool intro, bool preserveSp0Custom);
void updateLastPage();
void loadWav();
bool findSliderDefPageSlot(int chan, SettingArray arr, int8_t idx, int &page, int &slot);
int getDefaultFastFilterValue(int channel, SettingArray arr, int8_t idx);
void setDefaultFastFilterValue(int channel, SettingArray arr, int8_t idx, int value);
void setSliderDefForChannel(int channel);
FLASHMEM void initPageMutes();
FLASHMEM bool getMuteState(int channel);
FLASHMEM bool getMuteStateForUI(int channel);
FLASHMEM void setMuteState(int channel, bool muted);
FLASHMEM void unmuteAllChannels();
FLASHMEM void applyMutesAfterPMODSwitch();
void playTimerTick();
FLASHMEM void savePattern(bool autosave);
FLASHMEM void saveSamplePack(int pack);
FLASHMEM void loadPattern(bool autoload);
FLASHMEM void autoLoad();
FLASHMEM void autoSave();
void updateMixerGains(int i);
void setMixerGainSmooth(int index, int channel, float target, int steps);
void initFilterTransition(int index);
void forceAllMixerGainsToTarget();
void setFilters(FilterType filterType, int index, bool initial);
void setFilterDefaults(int channel);
static bool channelHasFreeverb(uint8_t chan);
static bool updateFilterPageAvailability(uint8_t /*chan*/);
static inline bool isWideFilterView2B();
static inline void getFilterSliderCols(uint8_t sliderIndex, uint8_t &x0, uint8_t &x1);
uint8_t scaleToDisplay(const SliderDefEntry& meta, uint8_t val);
uint8_t scaleFromDisplay(const SliderDefEntry& meta, uint8_t val);
uint8_t readSetting(SettingArray arr, int8_t idx, uint8_t chan);
void drawSliderName(uint8_t x0, uint8_t x1, const char* name, CRGB filtercol);
void drawCornerValueCustom(uint8_t encoderIndex, uint8_t val, const SliderDefEntry& meta);
void drawVerticalSlider(uint8_t x0, uint8_t x1, uint8_t val, uint8_t maxVal, CRGB baseColor, bool lowHighSlider, uint8_t sliderIndex, uint8_t page, bool switchtype);
void initSliders(uint8_t page, uint8_t chan);
void slider(uint8_t page);
void setDefaultFilterFromSlider(uint8_t page, uint8_t encoder);
void toggleDefaultFilterFromSlider(uint8_t page, uint8_t encoder);
void processAdjustments_new(uint8_t page);
void setNewFilters();
void showFilterPages(uint8_t chan);
void showFilterNames(uint8_t chan);
void updateFilterEncoderColors();
static inline uint8_t clampVel(int v);
static inline void placeGenNote(unsigned int c, int row, uint8_t ch, int vel, uint8_t prob, uint8_t cond);
bool loadSampleManifest();
bool scanAndWriteManifest();
unsigned int sampleBrowserHashName(const char* s);
static bool hasWavExt(const char* name);
static void copyBaseName64(const char* rawName, char* out, size_t outSz);
static void sortNameBlock(char names[][SAMPLE_BROWSER_NAME_MAX], int n);
static void sortNameBlockWithSizes(char names[][SAMPLE_BROWSER_NAME_MAX], uint32_t sizes[], int n);
static void browseDirGoParent(int ch);
void sampleBrowserInvalidate();
int sampleBrowserBrowseIndexMax(int channel);
void sampleBrowserClampBrowseIndexAndHardware(int channel);
static bool sampleBrowserAppendFolderSegment(int channel, const char* name);
static void sampleBrowserGetLeafFolderName(int channel, char* out, size_t outSize);
uint8_t sampleBrowserEntryTypeAt(int idx);
bool sampleBrowserSelectionIsDirectory(int channel);
bool sampleBrowserSelectionIsFile(int channel);
static void sampleBrowserFinishFolderStep(int channel, unsigned int prevWavPos, const char* preferredFolderName);
void sampleBrowserRefreshList(int channel);
void sampleBrowserSyncBrowseFromStoredPath(int ch);
bool sampleBrowserIsLoadableSelection(int channel);
void sampleBrowserNavigatePress(int channel);
void sampleBrowserLastEncoderPress(int channel);
void sampleBrowserClearAll();
void generateNextNumericName(int folderIdx, char* outName, size_t outSize);
void buildSamplePath(int folderIdx, int fileIdx, char* out, size_t outSize);
void EEPROMgetLastFiles();
void loadSMPSettings();
void writeWavHeader(File &file, uint32_t sampleRate, uint8_t bitsPerSample, uint16_t numChannels);
void finalizeWavHeader(File &file, uint32_t dataSize);
void startRecordingRAM();
void flushAudioQueueToRAM2();
void stopRecordingRAM(int fnr, int snr);
void startFastRecord();
void flushAudioQueueToRAM();
void stopFastRecord();
void EEPROMsetLastFile();
void clearAllNotesOfChannel();
FLASHMEM void FastLEDclear();
static void ssLight(int x, int y, CRGB color);
FLASHMEM static void drawScreensaverMatrix();
FLASHMEM void FastLEDshow();
int getPage(int x);
void drawRandoms();
void generateRhythmicPattern(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void generateMelodicPattern(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void generateBassOrMelody(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void generateBassLine(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void generateMainMelody(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void generateContextAwareRhythmicPattern(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony, BasePagePattern* basePattern, int pageOffset);
void generateContextAwareMelodicPattern(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony, BasePagePattern* basePattern, int pageOffset);
int createHarmonicProgression(int baseNote, int pageOffset, HarmonicAnalysis harmony);
int createMelodicProgression(int baseNote, int pageOffset, HarmonicAnalysis harmony);
int createRhythmicProgression(int baseNote, int pageOffset, HarmonicAnalysis harmony);
void generateGenreTrack();
void setGenreBPM();
void applyBPMDirectly(int bpm);
FLASHMEM void generateTechnoPattern(unsigned int start, unsigned int end, unsigned int page);
FLASHMEM void generateHipHopPattern(unsigned int start, unsigned int end, unsigned int page);
FLASHMEM void generateDnBPattern(unsigned int start, unsigned int end, unsigned int page);
FLASHMEM void generateHousePattern(unsigned int start, unsigned int end, unsigned int page);
FLASHMEM void generateAmbientPattern(unsigned int start, unsigned int end, unsigned int page);
void generateBasicPattern(unsigned int start, unsigned int end, unsigned int channel, HarmonicAnalysis harmony);
void clearPage();
void clearPageX(int thatpage);
void resetAllAudioEffects();
void startNew();
int getFolderNumber(int value);
int getFileNumber(int value);
CRGB getCol(unsigned int g);
void setNote(uint16_t step,  uint8_t pitch, uint8_t channel, uint8_t velocity);
Note getNote(uint16_t step, uint8_t channel);
CRGB getPixelColor(uint8_t x, uint8_t y, unsigned long elapsed);
void runAnimation();
void generateSong();
void initLedStrip();
void setLedStripLength(int length);
int getLedStripLength();
void setLedStripEnabled(bool enabled);
bool getLedStripEnabled();
void triggerLedStripRipple(uint8_t channel);
void updateLedStrip();
void onNoteTriggered(uint8_t channel);
FLASHMEM void clearLedStripForScreensaver();
static inline int userChToInternalDrawR(int uch);
static inline int internalToUserChDrawR(int in);
static inline uint16_t pongSpeedToInterval(int speed);
static inline int pongIntervalToSpeed(uint16_t interval);
void menuRequestFullRedraw();
static inline bool takeMenuForceFullRedraw();
static int textPixelWidth_3x5(const char *text);
FLASHMEM static void drawEtcInfoPage();
static inline uint32_t crc32_update(uint32_t crc, uint8_t data);
static uint32_t crc32_compute(const uint8_t *data, size_t len);
static bool readLine(File &f, char *buf, size_t bufSize);
static int hexNibble(char c);
static bool decodeHexBytes(const char *hex, uint8_t *out, size_t outLen);
static void encodeHexBytes(const uint8_t *in, size_t inLen, char *out, size_t outSize);
void markSettingsBackupDirty();
FLASHMEM static bool writeSettingsBackupToSD();
FLASHMEM static bool readSettingsBackupFromSD(unsigned int &outSamplePackID, uint8_t *outBlock, size_t outBlockLen, uint8_t *outSp0Block, size_t outSp0BlockLen);
FLASHMEM void serviceSettingsBackup();
FLASHMEM void flushSettingsBackupNow();
FLASHMEM static uint16_t hfcNormalize256(uint16_t h);
FLASHMEM static uint16_t hfcMigrate22000To256(uint16_t oldv);
FLASHMEM static uint16_t hfcMigrate44200To256(uint16_t raw3);
FLASHMEM void loadMenuFromEEPROM();
void applyAudioSettingsFromGlobals();
void saveSingleModeToEEPROM(int index, int8_t value);
static void saveTransportDelayToEEPROM(int slotBase, int8_t value);
void saveSp0StateToEEPROM();
void loadSp0StateFromEEPROM();
FLASHMEM void showMenu();
FLASHMEM void showLookMenu();
FLASHMEM void showRecsMenu();
FLASHMEM void showMidiMenu();
FLASHMEM void showVolMenu();
FLASHMEM void showEtcMenu();
static inline CRGB dimIconColorFromText(CRGB textColor);
static inline CRGB menuTextColorFromCol(uint8_t colIndex);
static inline CRGB currentMenuParentTextColor();
static inline void drawLargeIndicatorCustom(CRGB color, int encoderNum);
static inline uint32_t hashEncoderPositions(const Mode *m);
FLASHMEM void drawMainSettingStatus(int setting);
FLASHMEM void drawAdditionalFeatures(int setting);
FLASHMEM void drawGenreSelection();
FLASHMEM bool handleAdditionalFeatureControls(int setting);
void switchMenu(int menuPosition);
void nextMenuPage();
void previousMenuPage();
void goToMenuPage(int page);
void resetMenuState();
void resetNewModeState();
void drawSimpleNotesView();
void drawLoopLength();
void drawLedModules();
void showNewFileScreen();
void showNewFileMode();
int getCurrentMenuMainSetting();
FLASHMEM void clearTextArea(int startX, int startY, int width);
static inline void drawMenuValue(const char* label, int x, int y, CRGB color);
FLASHMEM void drawRecChannelClear();
FLASHMEM void drawRecMode();
FLASHMEM void drawClockMode();
FLASHMEM void drawMidiVoiceSelect();
FLASHMEM void drawPreviewVol();
FLASHMEM void drawFastRecMode();
FLASHMEM void drawPatternMode();
FLASHMEM void drawFlowMode();
FLASHMEM void drawMidiTransport();
FLASHMEM void drawMidiSend();
unsigned long effectiveTransportSendDelayMs();
unsigned long effectiveTransportRecvDelayMs();
static inline void logMidiRxNoteOn(uint8_t ch, uint8_t pitch, uint8_t velocity);
static inline void logMidiRxNoteOff(uint8_t ch, uint8_t pitch, uint8_t velocity);
static inline void logMidiRxSimple(const char *msg);
static inline void logMidiRxPitchBend(uint8_t ch, uint16_t bend14);
static inline void logMidiRxSongPosition(uint16_t beats);
bool getBPMStable();
uint16_t getMidiClockTicks();
static void markExternalOne();
void midiClockTick();
static inline void configureMidiClockSend(float bpm, unsigned long nowMicros);
void updateMidiClockOutput();
void handleMidiClock();
void checkMidi();
void resetMidiClockState();
void resetMidiClockForTransportStart();
void myClock(unsigned long now_captured);
void MidiSendNoteOn(int pitch, int channel, int velocity);
void handleStop();
static int mapMidiToLogicalChannel(int midiChannel, uint8_t pitch);
void handleNoteOn(int ch, uint8_t pitch, uint8_t velocity);
void onBeatTick();
void handleNoteOff(uint8_t midiChannel, uint8_t pitch, uint8_t velocity);
void handleStart();
void armMasterTransportStartDelay();
void handleTimeCodeQuarterFrame(uint8_t data);
void handleSongPosition(uint16_t beats);
void setParams(ParameterType paramType, int index);
void handleWaveformChange(int index, unsigned int waveformType);
void setFiltersDefaultValues(int ch);
void setEnvelopeDefaultValues(int ch);
void setSynthDefaultValues(int ch);
void applySynthInstrumentPreset(int channel, int instrumentIdx);
void resetAllToDefaults();
bool isEncoder0PressedMode();
void setEncoder0PressedMode(bool state);
static bool findWavDataChunk(File &f, uint32_t &outStart, uint32_t &outSize);
static void stopPeakScan();
void startPeakScan(const char *path, bool resetPeaks);
static void servicePeakScan(uint32_t maxBytesThisCall);
void stopAllSetWavPreviewAudio();
FLASHMEM void previewSample(bool setMaxSampleLength);
static void loadEmptySampleToChannel(unsigned int sampleID);
FLASHMEM void loadSample(unsigned int packID, unsigned int sampleID);
static CRGB fileSizeToColor(uint32_t bytes);
static void drawSampleBrowserDepthVisual(int ch);
void showWave();
static void sampleLoadUiThrottled(uint8_t percent, bool enable, uint8_t &lastDrawn);
FLASHMEM void copySampleToSamplepack0(unsigned int channel, bool showLoadProgress);
void reversePreviewSample();
void loadPreviewToChannel(unsigned int targetChannel, bool showLoadProgress);
void arp_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void lead_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void keys_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void pad_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void organ_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void flute_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void wow_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void bass_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void brass_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
void chiptune_synth(int ch, int p1, int p2, int p3, int p4, int p5, int p6);
static inline uint8_t synthWaveformBeginType(int ch, int oscIdx);
void updateVals(int ch);
void playSound(int note, int ch);
static unsigned synthAutoOffMsForInstrument(int inst);
void autoOffActiveNotes();
void stopSound(int note, int ch);
void updateSynthVoice(int channel);
void switchSynthVoice(int typeValue, int ch, int p1,int p2, int p3, int p4, int p5, int p6);
void light_single(unsigned int matrixId, unsigned int x, unsigned int y, CRGB color);
void light(unsigned int x, unsigned int y, CRGB color);
CRGB getIndicatorColor(char colorCode);
CRGB getCurrentChannelColor();
CRGB applyHighlight(CRGB color, bool highlight);
CRGB normalizeToMaxBrightness(CRGB color);
static inline void getIndicatorXPositions(int encoderNum, int &x1, int &x2, int &x3);
void drawIndicator(char size, char colorCode, int encoderNum, bool highlight);
FLASHMEM void drawLowResCircle(int startX, int startY, CRGB color);
void drawFilterCheck(int mappedValue, FilterType fx, CRGB color);
void drawPlayButton();
void drawNoSD();
void drawBase();
FLASHMEM static void adjustPongAngle(int &vx, int &vy);
FLASHMEM void resetPongGame();
FLASHMEM static void initPongBall();
static bool pongNoteAt(int px, int py);
static void triggerPongCollision(int px, int py);
FLASHMEM void updatePongBall();
FLASHMEM void drawPongBall();
FLASHMEM void drawRecordingBorder();
FLASHMEM void drawBatteryWarning();
void drawStatus();
FLASHMEM void drawText(const char *text, int startX, int startY, CRGB color);
FLASHMEM void drawChar(char c, int x, int y, CRGB color);
FLASHMEM void drawNumber(float count, CRGB color, int topY);
FLASHMEM void drawVelocity();
FLASHMEM void drawCtrlVolumeOverlay(int volume);
FLASHMEM void drawInputGainOverlay(int gain, int maxGain);
FLASHMEM void drawChannelNrOverlay(int channelNum, int channelIdx);
FLASHMEM void drawSampleLoadOverlay(uint8_t progressPercent);
void drawPages();
FLASHMEM void drawTriggers();
void drawTimer();
FLASHMEM void drawCountIn();
int mapXtoPageOffset(int x);
void drawCursor();
FLASHMEM void drawVolume(unsigned int vol);
FLASHMEM void drawLineOutVolume(uint8_t level);
FLASHMEM void drawBrightness();
static inline void drawIcon7x12_P(const uint8_t *data, int ox, int oy, CRGB color, int yOffset);
FLASHMEM void showIconsAt(IconType ico, CRGB colors, int ox, int oy);
FLASHMEM void showIcons(IconType ico, CRGB colors);
void processPeaks();
void processRecPeaks();
void drawLoadingBar(int minval, int maxval, int currentval, CRGB color, CRGB fontColor, bool intro);
FLASHMEM void drawMidiArrow(bool direction, int x, int y, bool blink);
FLASHMEM void drawBPMWithReservedSpace(float bpm, CRGB color, int topY);
void drawBPMScreen();
void drawKnobColorDefault();
void showSongMode();

#endif // TOERN_PROTOTYPES_H
